apiVersion: apps/v1
kind: Deployment

metadata:
  name: service2-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: devekinandan/greeting-service2:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE3_URL
              value: "http://service-3:8080"
